<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="styles.css" type="text/css">
    <link rel="stylesheet" href="bootstrap.css" type="text/css">
      <link rel="stylesheet" href="bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="bootstrap-grid.css" type="text/css">
          <link rel="stylesheet" href="bootstrap-grid.min.css" type="text/css">
            <link rel="stylesheet" href="bootstrap-reboot.css" type="text/css">
              <link rel="stylesheet" href="bootstrap-reboot.min.css" type="text/css">
    <title></title>
</head>
<body>
<!-- Headrer of the page and navigation bar -->
<header>
    <h1 id="main-header">Help Page</h1>
</header>

<h2>How the App works:</h2>
<p>The goal of <strong>(App name)</strong> is to make the users journey more enjoyable.

    Talk about the app Talk about the app Talk about the app Talk about the app
    Talk about the app Talk about the app Talk about the app Talk about the app
    Talk about the app Talk about the app Talk about the app Talk about the app</p>

<h2>How does the ladder board system work?</h2>
<p>The ladder board show the top users, in other words the people that are stuck in
    traffic the longest. The longer you are stuck in traffic, the more points you receive.
    These points will allow you to win prizes and get gift cards. </p>

<h2>What is jam location?</h2>
<p>Jam location allows you to see the busiest locations around your area.
    This will therefore allow you to optimise your route and make your journey
    quicker and more enjoyable.</p>

<nav>
    <ul id="navigation">
        <li><a href="home.phtml">Home</a></li>
        <li><a href="leaderBoard.phtml">LeaderBoard</a></li>
        <li><a href="topLocationPoints.phtml">Jam Location</a></li>
        <li><a class="active" href="help.phtml">Help</a>
</nav>
</body>
</html>
