<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="styles.css" type="text/css">
    <link rel="stylesheet" href="styles.css" type="text/css">
    <link rel="stylesheet" href="bootstrap.css" type="text/css">
      <link rel="stylesheet" href="bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="bootstrap-grid.css" type="text/css">
          <link rel="stylesheet" href="bootstrap-grid.min.css" type="text/css">
            <link rel="stylesheet" href="bootstrap-reboot.css" type="text/css">
              <link rel="stylesheet" href="bootstrap-reboot.min.css" type="text/css">
    <title>Home Page</title>
</head>
<body>
<!-- Headrer of the page and navigation bar -->
<header>
    <h1 id="main-header">Profile</h1>
</header>
<span class="status">Status:</span>
<table class="status" border="1">
    <tr>
        <th>Position</th>
        <th>Name</th>
        <th>Points</th>
    </tr>
    <tr>
        <th>34th</th>
        <th>Abdi</th>
        <th>540</th>
    </tr>
</table>
<h2 class="recent-points">Recent points:</h2>

<p class="recent-points"">15 minutes on 14/10/2018 </p>
<p class="recent-points"">+50 points</p>
<p class="recent-points"">30 minutes on 20/10/2018 </p>
<p class="recent-points"">+100 points</p>

<nav>
    <ul id="navigation">
        <li><a class="active" href="home.phtml">Home</a></li>
        <li><a href="leaderBoard.phtml">LeaderBoard</a></li>
        <li><a href="topLocationPoints.phtml">Jam Location</a></li>
        <li><a href="help.phtml">Help</a>
</nav>
</body>
</html>
