<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" >
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="styles.css">
    <link rel="stylesheet" href="styles.css" type="text/css">
    <link rel="stylesheet" href="bootstrap.css" type="text/css">
      <link rel="stylesheet" href="bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="bootstrap-grid.css" type="text/css">
          <link rel="stylesheet" href="bootstrap-grid.min.css" type="text/css">
            <link rel="stylesheet" href="bootstrap-reboot.css" type="text/css">
              <link rel="stylesheet" href="bootstrap-reboot.min.css" type="text/css">
    <title>Log in</title>
</head>
<body id="contact-me-body">
<header>
    <h1 id="main-header">Log in</h1>
</header>

<div class="contact-form">
    <form action="formResult.php" method="post" >
        <input class="form-control" name="name" type="text"  placeholder="Enter UserName" required> <br>
        <input class="form-control" name="email" type="password"  placeholder="Enter Password" required> <br>

        <input class="form-control submit" type="submit" name="submit" value="Log in">

    </form>

</div>
</body>
</html>
