<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="styles.css" type="text/css">
    <link rel="stylesheet" href="styles.css" type="text/css">
    <link rel="stylesheet" href="bootstrap.css" type="text/css">
      <link rel="stylesheet" href="bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="bootstrap-grid.css" type="text/css">
          <link rel="stylesheet" href="bootstrap-grid.min.css" type="text/css">
            <link rel="stylesheet" href="bootstrap-reboot.css" type="text/css">
              <link rel="stylesheet" href="bootstrap-reboot.min.css" type="text/css">
              <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <title></title>
</head>
<body>
<!-- Headrer of the page and navigation bar -->
<header>
    <h1 id="main-header">Ladder Board</h1>
</header>
<div class="table">
    <table border="1">
        <tr>
            <th>Rank</th>
            <th>Name</th>
            <th>Points</th>
        </tr>
        <tr>
            <td>1</td>
            <td>Abdi</td>
            <td>540</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Jordan</td>
            <td>480</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Haashim</td>
            <td>350</td>
        </tr>
        <tr>
            <td>4</td>
            <td>Kumail</td>
            <td>255</td>
        </tr>
    </table>
</div>
<div class="container">
  <div class="row">
    <div id="" class="col-xs-1" style="border: thin solid black">
      Col 1
    </div>
    <div id="" class="col-xs-1" style="border: thin solid black">
      Col 2
    </div>
    <div id="" class="col-xs-1" style="border: thin solid black">
      Col 3
    </div>
    <div id="" class="col-xs-1" style="border: thin solid black">
      Col 4
    </div>
    <div id="" class="col-xs-1" style="border: thin solid black">
      Col 5
    </div>
    <div id="" class="col-xs-1" style="border: thin solid black">
      Col 6
    </div>
    <div id="" class="col-xs-1" style="border: thin solid black">
      Col 7
    </div>
    <div id="" class="col-xs-1" style="border: thin solid black">
      Col 8
    </div>
    <div id="" class="col-xs-1" style="border: thin solid black">
      Col 9
    </div>
    <div id="" class="col-xs-1" style="border: thin solid black">
      Col 10
    </div>
    <div id="" class="col-xs-1" style="border: thin solid black">
      Col 11
    </div>
    <div id="" class="col-xs-1" style="border: thin solid black">
      Col 12
    </div>
  </div>
</div>


<nav>
    <ul id="navigation">
        <li><a href="home.phtml">Home</a></li>
        <li><a class="active" href="leaderBoard.phtml">LeaderBoard</a></li>
        <li><a href="topLocationPoints.phtml">Jam Location</a></li>
        <li><a href="help.phtml">Help</a>
</nav>

</body>
</html>
