<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="styles.css" type="text/css">
    <title></title>
</head>
<body>
<!-- Headrer of the page and navigation bar -->
<header>
    <h1 id="main-header">Ladder Board</h1>
</header>
<div class="table">
    <table border="1">
        <tr>
            <th>Rank</th>
            <th>Name</th>
            <th>Points</th>
        </tr>
        <tr>
            <td>1</td>
            <td>Abdi</td>
            <td>540</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Jordan</td>
            <td>480</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Haashim</td>
            <td>350</td>
        </tr>
        <tr>
            <td>4</td>
            <td>Kumail</td>
            <td>255</td>
        </tr>
    </table>
</div>


<nav>
    <ul id="navigation">
        <li><a href="home.phtml">Home</a></li>
        <li><a class="active" href="leaderBoard.phtml">LeaderBoard</a></li>
        <li><a href="topLocationPoints.phtml">Jam Location</a></li>
        <li><a href="help.phtml">Help</a>
</nav>

</body>
</html>
