<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="styles.css" type="text/css">
    <title></title>
</head>
<body>
<!-- Headrer of the page and navigation bar -->
<header>
    <h1 id="main-header">Profile</h1>
</header>
<nav>
    <ul id="navigation">
        <li><a href="home.phtml">Home</a></li>
        <li><a href="leaderBoard.phtml">LeaderBoard</a></li>
        <li><a class="active" href="topLocationPoints.phtml">Jam Location</a></li>
        <li><a href="help.phtml">Help</a>
</nav>
</body>
</html>
